[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  external_node_modules = ["express", "mongoose", "bcryptjs", "jsonwebtoken"]
  node_bundler = "esbuild"

# Catch-all redirect for API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true