[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Credentials = "true"
    Content-Security-Policy = """
      default-src 'self' *;
      font-src 'self' data: https: *;
      img-src 'self' data: https: *;
      media-src 'self' data: https: *;
      connect-src 'self' *;
      style-src 'self' 'unsafe-inline' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
      worker-src 'self' blob:;
    """

[functions]
  external_node_modules = ["express", "mongoose", "jsonwebtoken", "bcryptjs", "cors"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"